// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdF3KmjppKE32gE__yFOSYUBa61uya5ic',
    appId: '1:366950844292:android:773bebb24d79c5c34bbfd1',
    messagingSenderId: '366950844292',
    projectId: 'easyhealth-96183',
    storageBucket: 'easyhealth-96183.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD30C0L2qGadiNL_YPRp2maaTg7laI1R7c',
    appId: '1:366950844292:ios:e0fa9c175186b64a4bbfd1',
    messagingSenderId: '366950844292',
    projectId: 'easyhealth-96183',
    storageBucket: 'easyhealth-96183.firebasestorage.app',
    iosBundleId: 'es.asanjim.easyhealth',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRvMEd_aFlFJKD7gZtYhqQUeQ0rwVUUNM',
    appId: '1:366950844292:web:7a836ceefa047bc84bbfd1',
    messagingSenderId: '366950844292',
    projectId: 'easyhealth-96183',
    authDomain: 'easyhealth-96183.firebaseapp.com',
    storageBucket: 'easyhealth-96183.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRvMEd_aFlFJKD7gZtYhqQUeQ0rwVUUNM',
    appId: '1:366950844292:web:2eda2ef08c9cbca34bbfd1',
    messagingSenderId: '366950844292',
    projectId: 'easyhealth-96183',
    authDomain: 'easyhealth-96183.firebaseapp.com',
    storageBucket: 'easyhealth-96183.firebasestorage.app',
  );
}
